name             'machine'
maintainer       'ActionML'
maintainer_email 'devops@actionml.com'
license          'All rights reserved'
description      'Installs/Configures machine'
long_description 'Installs/Configures machine'
version          '0.1.1'

# depends 'consul_kv'
depends 'aml'
depends 'docker', '~> 2.9.6'
depends 'chef-sugar', '~> 3.4.0'
