name             'machine'
maintainer       'ActionML'
maintainer_email 'devops@actionml.com'
license          'All rights reserved'
description      'Installs/Configures machine'
long_description 'Installs/Configures machine'
version          '0.2.0'

depends 'docker'
depends 'chef-sugar'
depends 'consul'
